### ISSUE TITLE
Schema generated is not deterministic.

### ISSUE THREAD

**Issue by ajeddeloh** [idubinskiy/schematyper#11]
Using the [Ignition schema](https://github.com/coreos/ignition/blob/01c039a5ce59acd39e5741713e59abfcb74d0782/schema/ignition.json) and running:
```
schematyper --package=types schema/ignition.json -o config/types/schema.go --root-type=Config
```
from the root of the Ignition source will sometimes generate schemas with `Passwd.PasswdUser.Groups` as of type `[]Group` (where `Group` is defined as `type Group string`) and sometimes as type `[]PasswdUserGroup` (where `PasswdUserGroup` is also defined as `type PasswdUserGroup string`)

These names should not change between runs.

To Reproduce:
1) Clone [Ignition](https://github.com/coreos/ignition)
2) Ensure `schematyper` is in your path
3) run `./generate && git diff` several times and note the schema it generates differs between runs

I suspect it has something to do with the fact that there are multiple things named "group".

Workaround:
Run `schematyper` until the ouptut matches what you expect.

**Comment by idubinskiy** [comment]
I will take a look at this tomorrow. Probably a case of some  internal slice or map needing a stable sort.

**Comment by idubinskiy** [comment]
@ajeddeloh This should be fixed now.
