### ISSUE TITLE
schematyper sometimes embed structs and sometimes does not.

### ISSUE THREAD

**Issue by ajeddeloh** [idubinskiy/schematyper#12]
Schematyper sometimes embeds structs and sometimes does not.

Repro:
Run `./generate` from [ignition](https://github.com/coreos/ignition) several times. Note the output is not deterministic.

This might have to do with the parent struct and the child struct having the same name?

**Comment by idubinskiy** [comment]
@ajeddeloh Should be fixed.

**Comment by ajeddeloh** [comment]
Confirmed fixed for me. Thanks for the fast fix!
