### ISSUE TITLE
`allOf` results in a `type <name> interface{}`

### ISSUE THREAD

**Issue by cgonyeo** [idubinskiy/schematyper#9]
I use an `allOf` in my schema to avoid a little duplication,
```
        "file": {
          "allOf": [
            {
              "$ref": "#/definitions/storage/definitions/node"
            },
            {
              "properties": {
                "contents": {
                  "$ref": "#/definitions/storage/definitions/file-contents"
                }
              }
            }
          ]
        },
```

This results in the `File` type in the generated code being this:

```
type File interface{}
```

If this is challenging to fix I could always duplicate the `node` properties in my schema.

Link to my schema again: http://lpaste.net/6280590999756472320

**Comment by idubinskiy** [comment]
@dgonyeo What do you think would be a good result for this? I can see a couple of options.

1. Embedding the types that are direct `$ref`s:
```go
type file struct {
    node
    contents fileContents
}
```

2. Copying the `$ref`s' fields to the new type.
```go
type file struct {
    filesystem string
    path string
    ...
    contents fileContents
}
```

I think I prefer the first one, but let me know if you think otherwise.

**Comment by cgonyeo** [comment]
I think the former more closely aligns with what I'd expect, but for my purposes either would work fine.

**Comment by idubinskiy** [comment]
I agree. Not sure how soon I can make that happen. Will give it a shot this weekend.

**Comment by idubinskiy** [comment]
@dgonyeo So I ended up going with a third option:

3. Creating an embedded type for every `allOf`, even the ones that aren't refs:
```go
type fileEmbedded1 {
    contents fileContents
}

type file struct {
    node
    fileEmbedded1
}
```

It's not the prettiest solution, but it seems cleaner in the sense that each schema is its own type (rather than attempting to merge schemas).

**Comment by cgonyeo** [comment]
That option works for me, but the embedded type for the non-`$ref` item in the `allOf` is an empty interface for me currently. http://lpaste.net/5378726937944391680

**Comment by idubinskiy** [comment]
Sorry, forgot to mention. Need to add `"type": "object"` to that one.

**Comment by cgonyeo** [comment]
Ah ok. Thanks so much for the help!
